# Generated by Django 3.2.15 on 2023-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodels',
            name='dependent_variable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
