# Generated by Django 3.2.14 on 2022-09-03 12:33

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trainedmodels_model_oh_encoders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodels',
            name='model_oh_encoders',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
