# Generated by Django 3.2.14 on 2022-09-04 06:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_trainedmodels_model_oh_encoders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedmodels',
            name='model_oh_encoders',
        ),
        migrations.AddField(
            model_name='trainedmodels',
            name='independent_variable',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodels',
            name='oh_encoders',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
